
version: "3.8"
services:

   app:
     build: .
     ports:
       - "8090:8090"

     depends_on:
       postgres:
         condition: service_healthy
     networks:
       - my-network



   postgres:
     image: postgres:latest
     environment:
        POSTGRES_USER: nayana
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: Microservice-Project
     ports:
       - "5433:5432"
     networks:
       - my-network
     volumes:
       - postgres-s-data:/var/lib/postgresql/data



networks:
  my-network:
    driver: bridge

volumes:
    postgres-s-data: