spring.application.name=Dockerdemo

server.port=8090
spring.datasource.url=jdbc:postgresql://postgres:5432/Microservice-Project
spring.datasource.username=nayana
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
